# Generated by Django 6.0 on 2025-12-27 09:48

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_version', models.PositiveIntegerField(default=1, editable=False)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable to put the game in maintenance mode')),
                ('timer_seconds', models.PositiveIntegerField(default=60, help_text='Game duration in seconds', validators=[django.core.validators.MinValueValidator(10)])),
                ('promo_score_threshold', models.PositiveIntegerField(default=100, help_text='Score required to earn a promo code', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Game Configuration',
                'verbose_name_plural': 'Game Configuration',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('prize_pool', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(db_index=True, max_length=13, unique=True, validators=[core.models.uzbek_phone_validator], verbose_name='Phone Number')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FruitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fruits/')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'weight'], name='core_fruitc_is_acti_add2e4_idx'), models.Index(fields=['order'], name='core_fruitc_order_951b6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('user_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('score_balls', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('best_combo', models.IntegerField(default=0)),
                ('anti_cheat_status', models.CharField(choices=[('clean', 'Clean'), ('ok', 'OK'), ('suspicious', 'Suspicious'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='clean', max_length=50)),
                ('log_json', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-score_balls'], name='core_gamese_score_b_8daee0_idx'), models.Index(fields=['-started_at'], name='core_gamese_started_c580aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TextCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='texts/')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=0)),
                ('correct_fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_cards', to='core.fruitcard')),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'weight'], name='core_textca_is_acti_85045a_idx'), models.Index(fields=['correct_fruit'], name='core_textca_correct_58e946_idx'), models.Index(fields=['order'], name='core_textca_order_f8d55e_idx')],
            },
        ),
    ]
