# Generated by Django 5.0.14 on 2026-02-10 06:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="E.g., 'Rate Game Difficulty', 'Favorite Season Theme'", max_length=200, verbose_name='Voting Title')),
                ('description', models.TextField(blank=True, help_text='Explain what this voting is about', verbose_name='Description')),
                ('category_type', models.CharField(choices=[('rating', 'Rating (1-5 stars)'), ('binary', 'Yes/No'), ('choice', 'Multiple Choice'), ('ranking', 'Ranking')], default='rating', max_length=20, verbose_name='Voting Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('related_difficulty', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Ranked')], null=True, verbose_name='Related Difficulty')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no end date', null=True, verbose_name='End Date')),
                ('show_in_profile', models.BooleanField(default=True, help_text='Display this voting in player profiles', verbose_name='Show in Profile')),
                ('allow_multiple_votes', models.BooleanField(default=False, help_text='Can users vote more than once?', verbose_name='Allow Multiple Votes')),
                ('require_authentication', models.BooleanField(default=True, help_text='Only authenticated users can vote', verbose_name='Require Login')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this voting', verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_votes', models.IntegerField(default=0, editable=False, verbose_name='Total Votes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_votings', to=settings.AUTH_USER_MODEL)),
                ('related_fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votings', to='core.fruitcard', verbose_name='Related Fruit Card')),
            ],
            options={
                'verbose_name': 'Voting Category',
                'verbose_name_plural': 'Voting Categories',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Option Text')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='voting_options/', verbose_name='Option Image')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('vote_count', models.IntegerField(default=0, editable=False, verbose_name='Votes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.votingcategory', verbose_name='Voting Category')),
            ],
            options={
                'verbose_name': 'Voting Option',
                'verbose_name_plural': 'Voting Options',
                'ordering': ['category', 'order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('binary_value', models.BooleanField(blank=True, null=True, verbose_name='Yes/No')),
                ('text_comment', models.TextField(blank=True, help_text='Optional comment or feedback', verbose_name='Comment')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='core.gamesession', verbose_name='Related Game Session')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.votingcategory', verbose_name='Category')),
                ('choice_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.votingoption', verbose_name='Choice')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_data', models.JSONField(default=dict, verbose_name='Results Data')),
                ('total_votes', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.votingcategory', verbose_name='Category')),
                ('most_popular_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.votingoption', verbose_name='Most Popular Choice')),
            ],
            options={
                'verbose_name': 'Voting Result',
                'verbose_name_plural': 'Voting Results',
            },
        ),
        migrations.AddIndex(
            model_name='votingcategory',
            index=models.Index(fields=['status', 'show_in_profile'], name='core_voting_status_e916ea_idx'),
        ),
        migrations.AddIndex(
            model_name='votingcategory',
            index=models.Index(fields=['order'], name='core_voting_order_2399d8_idx'),
        ),
        migrations.AddIndex(
            model_name='votingcategory',
            index=models.Index(fields=['-created_at'], name='core_voting_created_8daef7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votingoption',
            unique_together={('category', 'text')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['category', 'player'], name='core_vote_categor_e38314_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['-voted_at'], name='core_vote_voted_a_8a7d33_idx'),
        ),
    ]
