# Generated by Django 6.0.2 on 2026-02-11 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], unique=True, verbose_name='Difficulty Level')),
                ('name_en', models.CharField(default='Easy', max_length=50, verbose_name='Name (English)')),
                ('name_uz', models.CharField(default='Oson', max_length=50, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(default='Легко', max_length=50, verbose_name='Name (Russian)')),
                ('description_en', models.CharField(default='5 Points + Hints', max_length=200, verbose_name='Description (English)')),
                ('description_uz', models.CharField(default='5 ball + maslahatlar', max_length=200, verbose_name='Description (Uzbek)')),
                ('description_ru', models.CharField(default='5 очков + подсказки', max_length=200, verbose_name='Description (Russian)')),
                ('time_seconds', models.IntegerField(default=180, help_text='Game duration in seconds (30-600)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)])),
                ('base_points', models.IntegerField(default=5, help_text='Base points per match (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('level_multiplier', models.IntegerField(default=2, help_text='Score multiplier (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('combo_bonus_per_match', models.FloatField(default=1.5, help_text='Bonus points per combo match (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('shuffle_enabled', models.BooleanField(default=False, help_text='Should cards shuffle during gameplay?', verbose_name='Enable Shuffling')),
                ('shuffle_frequency', models.IntegerField(default=0, help_text='Shuffle every X seconds (0 = disabled, max 60)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('hints_enabled', models.BooleanField(default=True, help_text='Show hint pair at the start?', verbose_name='Show Hints')),
                ('combo_penalty_on_wrong', models.FloatField(default=0.5, help_text='Combo reduction multiplier on wrong match (0-1, e.g., 0.5 = keep half)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('card_color_text', models.CharField(default='linear-gradient(135deg, #667eea 0%, #764ba2 100%)', help_text='CSS gradient for text cards', max_length=50)),
                ('card_color_fruit', models.CharField(default='linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', help_text='CSS gradient for fruit cards', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this difficulty available to players?', verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Difficulty Setting',
                'verbose_name_plural': 'Difficulty Settings',
                'ordering': ['order', 'difficulty_level'],
            },
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='timer_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Default game duration in seconds (deprecated - use DifficultySettings)', validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
